set(CMAKE_CXX_STANDARD 20)

add_executable(0004a 0004a.cpp)
add_executable(0071a 0071a.cpp)
add_executable(0158a 0158a.cpp)
add_executable(0231a 0231a.cpp)
add_executable(0263a 0263a.cpp)

add_executable(0282a 0282a.cpp)
add_executable(0339b 0339b.cpp)
add_executable(0978a 0978a.cpp)

add_executable(0978b 0978b.cpp)
add_executable(1108a 1108a.cpp)
add_executable(1108b 1108b.cpp)
add_executable(1207a 1207a.cpp)
add_executable(1330a 1330a.cpp)

add_executable(1404a 1404a.cpp)
add_executable(1512c 1512c.cpp)
add_executable(1582a 1582a.cpp)

add_executable(1592a 1592a.cpp)
add_executable(1670b 1670b.cpp)
add_executable(1717b 1717b.cpp)
add_executable(1721b 1721b.cpp)
add_executable(1829a 1829a.cpp)

add_executable(1872a 1872a.cpp)
add_executable(1873c 1873c.cpp)
add_executable(1873d 1873d.cpp)

add_executable(2004b 2004b.cpp)
add_executable(2010a 2010a.cpp)
add_executable(2010b 2010b.cpp)
add_executable(2010c1 2010c1.cpp)
add_executable(2030a 2030a.cpp)

add_executable(0136a 0136a.cpp)
add_executable(0915a 0915a.cpp)
add_executable(0935b 0935b.cpp)
add_executable(1501a 1501a.cpp)
add_executable(1512b 1512b.cpp)